
- id: GarageMotionAutomation
  alias: Garage Motion Off
  trigger:
    platform: state
    entity_id: input_boolean.motion_garage
    to: 'on'
    for:
      seconds: 300
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.motion_garage

- id: SouthWestMotionAutomation
  alias: South West Motion Off
  trigger:
    platform: state
    entity_id: input_boolean.motion_southwest
    to: 'on'
    for:
      seconds: 300
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.motion_southwest

- id: SouthEastMotionAutomation
  alias: South East Motion Off
  trigger:
    platform: state
    entity_id: input_boolean.motion_southeast
    to: 'on'
    for:
      seconds: 300
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.motion_southeast


- id: HallwayMotionAutomation
  alias: Hallway Motion Off
  trigger:
    platform: state
    entity_id: input_boolean.motion_hallway
    to: 'on'
    for:
      seconds: 300
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.motion_hallway

- id: FrontDoorMotionAutomation 
  alias: FrontDoor Motion Off
  trigger:
    platform: state
    entity_id: input_boolean.motion_frontdoor
    to: 'on'
    for:
      seconds: 300
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.motion_frontdoor

        #cloud:
- id: StartHomeKit
  alias: 'Start HomeKit'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:02  # Waits 5 minutes
    - service: homekit.start

- id: CorrectHVAC
  alias: 'Redirect all MQTT HVAC set commands to the heatpumps'
  trigger:
    - platform: mqtt
      topic: heatpump/+/_set/+
  action:
    - service: mqtt.publish
      data_template:
        topic:  '{{ "heatpump/" + trigger.topic.split("/")[1] + "/command/state" }}'
        payload: >
          {% if trigger.topic.split("/")[-1] == "mode" %}
            {% if trigger.payload|upper == "OFF" %}
              {"power":"OFF"}
            {% elif trigger.payload == "fan_only" %}
              {"power":"ON","mode":"FAN"}
            {% else %}
              {{ "{\"power\":\"ON\",\"mode\":"|safe + trigger.payload|upper|tojson + "}" }}
            {% endif %}
          {% else %}
            {{ "{" + trigger.topic.split("/")[-1]|tojson + ":" + trigger.payload|tojson + "}" }}
          {% endif %}
