homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 67
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Brisbane
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages/
  auth_providers:
    - type: homeassistant
      #   - type: legacy_api_password


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
        javascript_version: latest

        #emulated_hue:
        #  host_ip: 192.168.22.13
        #  expose_by_default: true
        #  listen_port: 80

# Enables configuration UI
config:
http:
    use_x_forwarded_for: true
    #    external_url: https://ha.itsmy.io
    trusted_proxies:
     - 192.168.22.1
    ip_ban_enabled: true
    login_attempts_threshold: 5
  # Uncomment this to add a password (recommended!)
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123 
  #  trusted_networks:
    #    - 127.0.0.1
      #    - ::1
      #    - 192.168.22.0/24
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - belkin_wemo

wemo:
  static:
    - 192.168.22.30
    - 192.168.22.31
    - 192.168.22.32
    - 192.168.22.33


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

map:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
#tts:
#  - platform: google

group: !include groups.yaml
automation: !include automations.yaml

sensor power:
  - platform: pvoutput
    system_id: !secret pvoutput_systemid
    api_key: !secret pvoutput_api
    scan_interval: 150
  - platform: template
    sensors:
      power_consumption:
        value_template: '{% if is_state_attr("sensor.pvoutput", "power_consumption", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_consumption }}{% endif %}'
        friendly_name: 'Using'
        unit_of_measurement: 'Watt'
      energy_consumption:
        value_template: '{{ "%0.1f"|format(states.sensor.pvoutput.attributes.energy_consumption|float/1000) }}'
        friendly_name: 'Used'
        unit_of_measurement: 'kWh'
      power_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
        friendly_name: 'Generating'
        unit_of_measurement: 'Watt'
      energy_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
        friendly_name: 'Generated'
        unit_of_measurement: 'kWh'

sensor wemo:
  - platform: template
    sensors:
      laundry_current_consumption:
        friendly_name: 'Laundry Current Consumption'  
        unit_of_measurement: 'w'
        value_template: '{{ states.switch.laundry.attributes["current_power_w"] | round(-1) }}'


#sensor garage_door:
# - platform: rest
#   resource: http://jeeves:8080/
#   name: Garage Door
#   value_template: '{{ value_json.State }}'

#switch garage_door_ctrl:
#  - platform: rest
#    resource: http://jeeves:8080/
#    name: Garage Door Control
#    is_on_template: '{{ value_json.State == Opened }}'
#    body_on: '{"action": "true"}'
#    body_off: '{"action": "false"}'

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml


input_boolean:
   motion_garage:
      name: Garage Motion Sensor
      initial: off
      icon: mdi:cctv
   motion_southwest:
      name: South West Motion Sensor
      initial: off
      icon: mdi:cctv
   motion_southeast:
      name: South East Motion Sensor
      initial: off
      icon: mdi:cctv
   motion_hallway:
      name: Hallway Motion Sensor
      initial: off
      icon: mdi:cctv

   motion_frontdoor:
      name: Front Door Sensor
      initial: off
      icon: mdi:cctv

cloud:

deconz:
  host: 192.168.22.25
  port: 8080

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave
  polling_interval: 60000

#emulated_hue:
#  host_ip: 192.168.22.13
#  listen_port: 80
#  expose_by_default: false
#  entities:
#    switch.aeotec_zw116_nano_switch_switch:
#      name: "Bedroom Light"
#      hidden: false
#    light.back_light:
#      name: "Back light"
#      hidden: false
#    light.patio_light:
#      name: "Patio Light"
#      hidden: false
#    switch.stereo:
#      name: "Stereo"
#      hidden: false
#    switch.computer_2:
#      name: "Computer"
#      hidden: false

light:
  - platform: flux_led
    devices:
      172.22.22.41:
        name: Led Strip1
        mode: rgbw

tplink:
  discovery: true
  switch:
    - host: 172.22.22.30
    - host: 172.22.22.31

vacuum:
  - platform: xiaomi_miio
    host: 192.168.22.14
    token: 5a32776b56656d417568754c52763670
    name: charlie


system_health:

camera:
  - platform: xeoma
    host: http://vision.home.our-lan.com:10090
    cameras:
      - image_name: catcam
        name: Cat Camera
      - image_name: image0
        name: Garage Camera
      - image_name: image1
        name: Hallway Camera
      - image_name: image2
        name: East Camera
      - image_name: image3
        name: West Camera
      - image_name: image4
        name: Front Door Camera

switch:
  - platform: wake_on_lan
    name: "Office Computer"
    mac: "E0:D5:5E:84:D2:28" 
    host: 192.168.22.22

envisalink:
    host: 192.168.22.16
    user_name: user
    password: !secret alarmsystem
    panel_type: DSC
    evl_version: 4
    keepalive_interval: 60
    zonedump_interval: 30
    timeout: 10
    partitions: 
        1:
            name: "Home Alarm"
    zones:
        1: 
            name: "Hallway"
            type: 'motion'
        2:
            name: "Kitchen"
            type: "motion"
        3:
            name: "Master Bedroom"
            type: "motion"
        6:
            name: "Tamper"
            type: "opening"
        5:
            name: "Smoke Alarm"
            type: "smoke"
mqtt:
    broker: hass.home.our-lan.com
    discovery: true
    discovery_prefix: homeassistant

plant:
    FrontYard:
        sensors:
            moisture: sensor.grass_moisture
            battery: sensor.grass_battery
            temperature: sensor.grass_temperature
            brightness: sensor.grass_light
            conductivity: sensor.grass_conductivity
    SideYard:
         sensors:
             moisture: sensor.sideyard_moisture
             battery: sensor.sideyard_battery
             temperature: sensor.sideyard_temperature
             brightness: sensor.sideyard_light
             conductivity: sensor.sideyard_conductivity


homekit:
    auto_start: false
    filter:
        exclude_domains:
            - device_tracker
            - medi_player
            - automation

alexa:
  smart_home:
    filter:
      include_domains:
        - switch
        - light
        - climate

climate:
      platform: mqtt
      modes:
        - "off"
        - heat
        - dry
        - cool
        - fan_only
        - auto
      fan_modes:
        - "1"
        - "3"
      current_temperature_template: "{{ value_json.room_temp }}"
      temperature_state_template: "{{ value_json.temp }}"
      fan_mode_state_template: "{{ value_json.fan }}"
      #payload_available: 1
      #payload_not_available: 0
      mode_state_template: >
        {% if value_json.power == "OFF" %}
          off
        {% elif value_json.mode == "FAN" %}
          fan_only
        {% else %}
          {{ value_json.mode|lower }}
        {% endif %}
      name: "AirCon"
      current_temperature_topic: "heatpump/ducted/state"
      #availability_topic: "heatpump/ducted/connected"
      temperature_command_topic: "heatpump/ducted/_set/temp"
      temperature_state_topic: "heatpump/ducted/state"
      fan_mode_command_topic: "heatpump/ducted/_set/fan"
      fan_mode_state_topic: "heatpump/ducted/state"
      mode_command_topic: "heatpump/ducted/_set/mode"
      mode_state_topic: "heatpump/ducted/state"

litter_robot:
  username: !secret litter-robot-username
  password: !secret litter-robot-password
  scan_interval: 120

